// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flqexbwervowvqltuyrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscWV4YndlcnZvd3ZxbHR1eXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTY4MTMsImV4cCI6MjA3MDEzMjgxM30.WylMKPbMxmMvprh_64iQ0rZ2MdxzwNiZ4efYYSXFwCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});